version: '3.8'

services:
  web:
    build: .
    ports:
      - "8083:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:password@db:3306/gestioncontrat
    command: >
      sh -c "composer install &&
             npm install &&
             yarn install &&
             yarn encore dev &&
             php bin/console doctrine:database:create --if-not-exists &&
             php bin/console doctrine:migrations:migrate --no-interaction &&
             apache2-foreground"
    networks:
      - symfony

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gestioncontrat
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db
    networks:
      - symfony

volumes:
  db_data:

networks:
  symfony:
